# SET ( CLI_ELF
#   "${CMAKE_PROJECT_NAME}_cli-${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.out"
#   )
# 
# SET ( SRV_ELF
#   "${CMAKE_PROJECT_NAME}_srv-${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.out"
#   )
# 
# 
# 
# 
# 
# ADD_EXECUTABLE( ${OUTPUT_ELF}_cli src/mq_src/mq_cli.cpp )
# if (DEFINED DEPENDENCY_LIST) 
#   ADD_DEPENDENCIES(${OUTPUT_ELF} ${DEPENDENCY_LIST})
# endif()
# TARGET_INCLUDE_DIRECTORIES (${OUTPUT_ELF}_cli PUBLIC ${INCLUDE_DIR} )
# 
# ADD_EXECUTABLE( ${OUTPUT_ELF}_srv src/mq_src/mq_srv.cpp )
# if (DEFINED DEPENDENCY_LIST) 
#   ADD_DEPENDENCIES(${OUTPUT_ELF} ${DEPENDENCY_LIST})
# endif()
# TARGET_INCLUDE_DIRECTORIES (${OUTPUT_ELF}_srv PUBLIC ${INCLUDE_DIR} )
# 
